[default]
model_name = "EEGNet"  # "EEGNet" or "DeepConvNet"
activation = "relu"  # "relu" or "elu" or "leaky_relu"
lr = 0.001  # learning rate
weight_decay = 0.0001 # weight decay
dropout_prob = 0.5  # dropout rate
epochs = 300
batch_size = 64
use_aug = false

[specific.EEGNet]
spatial_filter_depth = 4
temporal_filter_size_1 = 16
temporal_filter_size_2 = 64

[specific.DeepConvNet]
channel_list = [25, 50, 100, 200]

[[experiment]]

name = "EEGNet_activation"
enable = false
model_name = "EEGNet"
experiment = "activation"
value = ["relu", "elu", "leaky_relu"]

[[experiment]]

name = "DeepConvNet_activation"
enable = false
model_name = "DeepConvNet"
experiment = "activation"
value = ["relu", "elu", "leaky_relu"]

[[experiment]]

name = "EEGNet_augmentation"
enable = false
model_name = "EEGNet"
experiment = "use_aug"
epochs = 500
value = [true]
