[default]
model_name = "EEGNet"  # "EEGNet" or "DeepConvNet"
activation = "relu"  # "relu" or "elu" or "leaky_relu"
lr = 0.001  # learning rate
weight_decay = 0.001  # weight decay
dropout_prob = 0.5  # dropout rate
epochs = 300

[specific.EEGNet]
spatial_filter_depth = 2
temporal_filter_size_1 = 16
temporal_filter_size_2 = 32

[specific.DeepConvNet]
channel_list = [25, 50, 100, 200]

[[experiment]]

name = "EEGNet_activation"
enable = true
model_name = "EEGNet"
experiment = "activation"
value = ["relu", "elu", "leaky_relu"]

[[experiment]]

name = "DeepConvNet_activation"
enable = true
model_name = "DeepConvNet"
experiment = "activation"
value = ["relu", "elu", "leaky_relu"]